### ISSUE TITLE
Lost 99% FTM on solidly.exchange transaction

### ISSUE THREAD

**Issue by Happyheart111** [solidlyexchange/solidly.exchange#13]
I tried to swap FTM to SOLID on Solidly.exchange using Metamask and I lost 99% FTM. Metamask support told me that it happenned inside the transaction on the solidly.exchange website.  Somebody could help me? 
https://ftmscan.com/tx/0x4760138e13a1caed36832de91be94c8f8ae2a2985193829c9ef9717cc8a22e37

**Comment by antonnell** [comment]
Hey bud, sorry you got hit with that.

You can follow on this issue for some more context: https://github.com/solidlyexchange/solidly/issues/57

We've made improvements on the quoting system to help with failing calls due to RPC errors.
Displaying stable vs variable routing on swap quote for a second sanity check to users.
We've also included Price Impact for people that don't check the output amount before swapping.
Perhaps some more improvements going forward as well, we'll see what we come up with.
